import yaml

from snakemake.utils import min_version, validate

min_version("9.19")


# !!!!! IMPORTANT !!!!!
# Define pathvars for all user resource files and result files
# This allows users to re-wire how the module is used in their workflow with ease.
pathvars:
    # User resources
    shapes="<resources>/user/{shapes}/shapes.parquet",
    # Module results
    annual_heat_demand="<results>/{shapes}/annual/heat_demand_twh.parquet",
    heat_demand="<results>/{shapes}/aggregated/heat_demand.parquet",
    heat_pump_cop="<results>/{shapes}/aggregated/heat_pump_cop.parquet",
    heat_pump_electricity_demand="<results>/{shapes}/aggregated/heat_pump_electricity_demand.parquet",
    heat_demand_visualization="<results>/{shapes}/visualization/heat_demand.html",


# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)


wildcard_constraints:
    ghsl_epoch="|".join(str(i) for i in internal["resources"]["ghsl"]["epochs"]),
    ghsl_resolution="|".join(
        str(i) for i in internal["resources"]["ghsl"]["resolutions"]
    ),


# Add all your includes here.
include: "rules/_utils.smk"
include: "rules/automatic.smk"
include: "rules/prepare.smk"
include: "rules/baseline.smk"
include: "rules/annual_heat_demand.smk"
include: "rules/heat_timeseries.smk"
include: "rules/heat_pump_cop.smk"


# Add additional files to be delivered alongside the workflow here.
# This is needed e.g. for python code files that are never
# explicitly used as a script or input in a snakemake rule.
workflow.source_path("scripts/_schemas.py")
workflow.source_path("scripts/_jrc.py")
workflow.source_path("scripts/_che.py")
workflow.source_path("scripts/_ecuk.py")
workflow.source_path("scripts/_plots.py")
workflow.source_path("scripts/_utils.py")

# Run additional check on configuration / settings
additional_config_validation()


rule all:
    default_target: True
    output:
        "INVALID",
    log:
        stderr="<logs>/all.stderr",
    message:
        "ERROR: Invalid `rule all:` call"
    shell:
        'echo "This workflow must be called as a snakemake module." > {log.stderr}'
