# Emulate a user configuring the module.
configfile: workflow.source_path("./test_config.yaml")


# Emulate how another workflow might create shape inputs for this module.
rule create_external_shapes:
    output:
        "resources/user/test/shapes.parquet",
    run:
        import geopandas as gpd
        from shapely.geometry import box

        shapes = gpd.GeoDataFrame(
            {
                "shape_id": ["NLD"],
                "country_id": ["NLD"],
                "shape_class": ["land"],
                "geometry": [box(3, 50, 8, 54)],
            },
            crs="EPSG:4326",
        )
        shapes.to_parquet(output[0])


# Import the module and configure it.
module module_euro_building_heat:
    pathvars:
        # Redirect specific user resources (inputs)
        shapes=rules.create_external_shapes.output[0],
        # Redirect specific module results (outputs)
        heat_demand="results/output/{shapes}/heat_demand.parquet",
        # Redirect intermediate files that are internal to the module
        logs="resources/module/logs",
        resources="resources/module/resources",
        results="resources/module/results",
    snakefile:
        "../../workflow/Snakefile"
    config:
        config["module_euro_building_heat"]


# Rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_euro_building_heat as module_euro_building_heat_*


# Request something from the module.
rule all:
    default_target: True
    input:
        "results/output/test/heat_demand.parquet",
    message:
        "A generic dry-run test case for the heat demand module."
