# Module settings that users cannot modify.
resources:
  jrc:
    use_version: 2023
    versions: [2015, 2021, 2023]
    url: https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/JRC-IDEES/{folder}/{file}
    spatial_scope:
      - AT
      - BE
      - BG
      - CY
      - CZ
      - DE
      - DK
      - EE
      - EL
      - ES
      - FI
      - FR
      - HR
      - HU
      - IE
      - IT
      - LT
      - LU
      - LV
      - MT
      - NL
      - PL
      - PT
      - RO
      - SE
      - SI
      - SK
      - UK  # Only 2015
  automatic:
    when2heat_params: https://zenodo.org/records/10965295/files/{dataset}?download=1
    heat_pump_characteristics: https://zenodo.org/records/20926669/files/heat_pump_characteristics.nc
    population: https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_POP_GLOBE_R2023A
    population_epochs: [1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030]
    eurostat:
      energy-balance: https://zenodo.org/records/20926669/files/estat_nrg_bal_c.tsv.gz
      hh-end-use: https://zenodo.org/records/20926669/files/estat_nrg_d_hhq.tsv.gz
    CHE:
      end-use: https://zenodo.org/records/20926669/files/CHE_energy_consumption_households.xlsx
      energy-balance: https://zenodo.org/records/20926669/files/CHE_energy_balance.xlsx
      industry-energy-balance: https://zenodo.org/records/20926669/files/CHE_energy_consumption_industry.xlsx
    GBR:
      end_use_zip: https://zenodo.org/records/20926669/files/GBR_End_Use_tables.zip
scope:
  datasets:
    annual_energy_balance:
      proxy_config: annual_energy_balance
      proxy_requires_shape_population: true
      countries:
        - ALB
        - AUT
        - BEL
        - BGR
        - BIH
        - CHE
        - CYP
        - CZE
        - DEU
        - DNK
        - EST
        - FIN
        - FRA
        - GBR
        - GEO
        - GRC
        - HRV
        - HUN
        - IRL
        - ISL
        - ITA
        - LVA
        - LTU
        - LUX
        - MDA
        - MKD
        - MLT
        - MNE
        - NLD
        - NOR
        - POL
        - PRT
        - ROU
        - SRB
        - SVK
        - SVN
        - ESP
        - SWE
        - TUR
        - UKR
    household_end_use:
      proxy_config: household_end_use
      countries:
        - ALB
        - AUT
        - BEL
        - BGR
        - BIH
        - CHE
        - CYP
        - CZE
        - DEU
        - DNK
        - EST
        - FIN
        - FRA
        - GBR
        - GEO
        - GRC
        - HRV
        - HUN
        - IRL
        - ITA
        - LVA
        - LTU
        - LUX
        - MDA
        - MKD
        - MLT
        - MNE
        - NLD
        - NOR
        - POL
        - PRT
        - ROU
        - SRB
        - SVK
        - SVN
        - ESP
        - SWE
        - TUR
        - UKR
    commercial_end_use:
      proxy_config: jrc_idees
      countries:
        - AUT
        - BEL
        - BGR
        - HRV
        - CYP
        - CZE
        - DNK
        - EST
        - FIN
        - FRA
        - DEU
        - GRC
        - HUN
        - IRL
        - ITA
        - LVA
        - LTU
        - LUX
        - NLD
        - MLT
        - POL
        - PRT
        - ROU
        - SVK
        - SVN
        - ESP
        - SWE
        - GBR
        - CHE
